server:
  port: 8070

spring:
  h2:
    console:
      enabled: true
      path: /test_db


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/mzc_project/test_db;AUTO_SERVER=TRUE
    username: hnjng
    password: 101630